# Generated by Django 6.0.1 on 2026-01-13 18:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('Precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
            ],
        ),
    ]
