# Generated by Django 4.2.11 on 2026-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default=1, upload_to='categorias/'),
            preserve_default=False,
        ),
    ]
