# Generated by Django 4.2.11 on 2026-01-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_categoria_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='imagen',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='Precio',
        ),
    ]
