# Generated by Django 4.2.11 on 2026-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_imagen_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
