# Generated by Django 6.0.1 on 2026-02-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_fix_categoria_nombre_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_column='Nombre', max_length=100),
        ),
    ]
