# Generated by Django 6.0.1 on 2026-01-12 23:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
    ]
